#!/bin/bash

BACKDIR="$HOME/Backup"

# バックアップディレクトリの確認
if [ ! -d $BACKDIR ];then
    mkdir -p $BACKDIR
fi

# バックアップディレクトリの確認
DATE=`date "+%y%m%d-%H%M%S"`
mkdir -p $BACKDIR/$DATE
echo "=======Backup Now======="
for j in $@; do
  if [ -e $j ]; then
    echo "cp -rp $1 $BACKDIR/$DATE"
    cp -rp $1 $BACKDIR/$DATE
  else
    echo "$j : not found"
  fi
done

